const LIST_POKEMON_REQUEST_SUCCESS = "LIST_POKEMON_REQUEST_SUCCESS";
const LIST_POKEMON_REQUEST_FAILURE = "LIST_POKEMON_REQUEST_FAILURE";
const DETAILS_POKEMON_REQUEST_SUCCESS = "DETAILS_POKEMON_REQUEST_SUCCESS";
const DETAILS_POKEMON_REQUEST_FAILURE = "DETAILS_POKEMON_REQUEST_FAILURE";

const HomePageAction = {
	LIST_POKEMON_REQUEST_SUCCESS,
	LIST_POKEMON_REQUEST_FAILURE,
	DETAILS_POKEMON_REQUEST_SUCCESS,
	DETAILS_POKEMON_REQUEST_FAILURE,
};

export default HomePageAction;